# Generated by Django 3.0.2 on 2022-11-06 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContraIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemption', models.CharField(choices=[('None', 'None'), ('Relative', 'Relative '), ('Absolute', 'Absolute '), ('Temporary', 'Temporary ')], default='None', max_length=20)),
                ('start_date', models.DateField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='adminMedInt', to=settings.AUTH_USER_MODEL)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ActiveIngredients')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('hc_reg_number', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_doctor', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD10_code', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default='0')),
                ('units', models.CharField(choices=[('mg', 'mg'), ('g', 'g ')], default='1', max_length=5)),
                ('schedule', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('active_ingridients', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ActiveIngredients')),
                ('admin', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='MRadmin', to=settings.AUTH_USER_MODEL)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ICD10')),
                ('doctor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='MRdoctor', to=settings.AUTH_USER_MODEL)),
                ('dosage_form', models.ForeignKey(default='tablet', on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Dosage')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.IntegerField(default='0')),
                ('units', models.CharField(choices=[('mg', 'mg'), ('g', 'g ')], default='1', max_length=5)),
                ('schedule', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('active_ingridients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ActiveIngredients')),
                ('dosage_form', models.ForeignKey(default='Tablet', on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Dosage')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=5)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('dob', models.DateField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.City')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('reg_number', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pharm_admin', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pharm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=5)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('license_number', models.CharField(max_length=20)),
                ('pharmacist_name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacyAdmin', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.City')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='11', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.City')),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contra_indication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ContraIndication')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.MedicalRecord')),
                ('pharmacist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('repeat', models.IntegerField(default='0')),
                ('repeat_left', models.CharField(default=0, max_length=2)),
                ('quantity', models.IntegerField(default='1')),
                ('comment', models.TextField(max_length=200)),
                ('dispensed_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('dispensed', 'Dispensed'), ('prescribed', 'Prescribed')], default='prescribed', max_length=10)),
                ('doctor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Dosage')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Patient')),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Pharmacist')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Province'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Suburb'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Pharmacy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Province'),
        ),
        migrations.AddField(
            model_name='patient',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Suburb'),
        ),
        migrations.CreateModel(
            name='MedPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=5)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.City')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Province')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Suburb')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medication_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='ePrescribe.Medication'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Patient'),
        ),
        migrations.CreateModel(
            name='MedicalInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Doctor')),
                ('medicine_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine1', to='ePrescribe.ActiveIngredients')),
                ('medicine_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ActiveIngredients')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_allergies', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('chronic_med_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ICD10')),
                ('current_chronic_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ActiveIngredients')),
                ('doctor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.MedPractice', to_field='reference'),
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contra_indication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.ContraIndication')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.MedicalRecord')),
                ('pharmacist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='contraindication',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Patient'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.Province'),
        ),
    ]
